spring.application.name=eccomerce
# ===============================
# Server
# ===============================
server.port=8080

# ===============================
# MongoDB Atlas
# lRKdkfga0ptPaUUG
# mongodb+srv://czsubham_db_user:lRKdkfga0ptPaUUG@cluster0.k5agxsq.mongodb.net/?appName=Cluster0
# ===============================
spring.data.mongodb.uri= mongodb+srv://czsubham_db_user:lRKdkfga0ptPaUUG@cluster0.k5agxsq.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=eccomerce
# ===============================
# JWT Configuration
jwt.secret=subham_super_secret_key_minimum_32_characters_long!!
jwt.access-token-expiry=900000
jwt.refresh-token-expiry=604800000
spring.security.user.name=disabled
spring.security.user.password=disabled


#spring.security.enabled=false


# ===============================
# Logging (optional)
# ===============================
#logging.level.org.springframework.security=INFO
