spring.application.name=eccomerce
# ===============================
# Server
# ===============================
server.port=8080

# ===============================
# MongoDB Atlas
# lRKdkfga0ptPaUUG
# mongodb+srv://czsubham_db_user:lRKdkfga0ptPaUUG@cluster0.k5agxsq.mongodb.net/?appName=Cluster0
# ===============================
spring.data.mongodb.uri= mongodb+srv://czsubham_db_user:lRKdkfga0ptPaUUG@cluster0.k5agxsq.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=eccomerce
# ===============================
# JWT Configuration
jwt.secret=subham_super_secret_key_minimum_32_characters_long!!
jwt.access-token-expiry=900000
jwt.refresh-token-expiry=604800000
spring.security.user.name=disabled
spring.security.user.password=disabled


# RedPanda Cloud (same URL as notification app)
spring.kafka.bootstrap-servers=d80205rqq91v3m2mvkhg.any.us-east-1.mpx.prd.cloud.redpanda.com:9092
spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=SCRAM-SHA-256
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="eccomerce_user" password="TestKafkaCz@123";

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.producer.properties.enable.idempotence=true

#spring.security.enabled=false
# eccomerce_spring for microservice level internal calls
internal.service.key=my-internal-secret-key-2026



# Local Redis (Docker)
spring.data.redis.host=localhost
spring.data.redis.port=6379

# OTP Config
otp.expiry.minutes=5
otp.max.attempts=3
otp.resend.cooldown.seconds=30

# ===============================
# Logging (optional)
# ===============================
logging.level.org.springframework.security=DEBUG
